# Generated by Django 3.2.7 on 2021-09-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='itemStatus',
            field=models.CharField(choices=[(0, 'BOUGHT'), (1, 'PENDING'), (2, 'NOT AVAILABLE')], default='PENDING', max_length=400),
        ),
    ]
