# Generated by Django 3.2.7 on 2021-09-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20210903_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='date',
            new_name='dueDate',
        ),
    ]
